### PR TITLE
Weather app

### PR DESCRIPTION
**Pull request by MrSayyod**
- Not committed “console.log” into repo;
- Not used “Window.alert()” or “Window.confirm()”;
- .lock files are in the repository to avoid problems with future versions of the dependencies;
- Used webpack;
- Included all webpack related packages in “devDependencies”;
- Added node_modules dir to .gitignore.

### CODE REVIEW

**Review by NtwaliHeritier — COMMENTED** [review]
### **STATUS: INVALID❌❌❌**

Hello @MrSayyod, 
Great work on this project👏
However, I have to invalidate the project, because the readme file doesn't explain how to set up and run the app locally.

Kindly fix it and ask for another review👍👍

Happy coding💻💻

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Sayyod Saidov** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] In your package.json file, add the next:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  }
```
- [x]  changes the page appearance based on the received data
- [x]  It should have a toggle control to determine if the result will be shown in Celsius or Fahrenheit.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by MrSayyod** [comment]
> ### Status: Changes Required ♻️
> **Hello Sayyod Saidov**
> Good job with the improvements for this project 💪 💪
> It meets most of the requirements 👏 👏 👏
> There are just a few details to improve before you can go ahead:
> 
> * [x]  In your package.json file, add the next:
> 
> ```
> "scripts": {
>     "dev": "webpack --mode development",
>     "build": "webpack --mode production",
>     "start": "webpack-dev-server --mode development --open" // optional
>   }
> ```
> 
> * [x]   changes the page appearance based on the received data
> * [x]   It should have a toggle control to determine if the result will be shown in Celsius or Fahrenheit.
> 
> Please request another review once you are ready! 👍
> 
> Happy coding ☺️
> 
> Oscar Andrés Russi Porras

- Mode types added into package.json file;
- page appearance changes due to weather type;
- Celcius/Fahrenheit toggler button added

**Review by andresporras3423 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello Sayyod Saidov** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
Don't forget to merge with the develop branch
 
Keep going like this  :clap: :clap:
 
Oscar Andrés Russi Porras

**Pull request merged**
